DavidNeves
AndreyJustino/API_Bank pull request #10
Opened 2024-10-11 23:33 UTC by Dav1dCode

2024-10-11 23:34 UTC, Dav1dCode reviewed
pull request alterações

2024-10-11 23:46 UTC, AndreyJustino commented on src/controller/transaction/deleteTransaction.controller.js
> +        const { id } = req.params;
você esta pedindo parametro mas vc não configuro la na rota pra aceita parametros

2024-10-11 23:46 UTC, AndreyJustino commented on src/controller/transaction/postTransaction.controller.js
> +        if (!amount || !type || !accountId) {
falto verificar se " accountId " esta vazio ou não

2024-10-11 23:46 UTC, AndreyJustino commented on src/controller/transaction/putTransaction.controller.js
> +        const { id } = req.params;
tem que configurar no arquivo de rota para aceitar parâmetros pela url

2024-10-11 23:46 UTC, AndreyJustino commented on src/controller/transaction/putTransaction.controller.js
> +        if (!amount || !type || !accountId) {
não poderia colocar o "id" junto desse if ?

2024-10-12 14:07 UTC, AndreyJustino requested changes
olhar comentarios

2024-10-14 14:22 UTC, merged